import = [ "/home/viktoreeej/dotfiles/.config/alacritty/colorschemes/tokyo-night.toml" ] # or tokyo-night-storm.toml

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 15.0

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "BoldItalic"

[font.italic]
family = "CaskaydiaCove NerdFont"
style = "MediumItalic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "medium"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.6

[window.padding]
x = 10
y = 10
